"""empty message

Revision ID: f5c595e19c07
Revises: 
Create Date: 2020-08-13 17:30:55.801652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5c595e19c07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'nif_funded')
    op.alter_column('publications', 'nif_likelihood', new_column_name='nif_assoc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('nif_funded', sa.BOOLEAN(), nullable=True))
    op.alter_column('publications', 'nif_assoc', new_column_name='nif_likelihood')
    # ### end Alembic commands ###
